CREATE TABLE APT_COMPLEX(
	COMPLEX_ID NUMBER PRIMARY KEY,
	COMPLEX_ADDRESS VARCHAR2(300) NOT NULL,
	COMPLEX_LAT NUMBER NOT NULL,
	COMPLEX_LNG NUMBER NOT NULL,
	COMPLEX_APARTNAME VARCHAR2(50) NOT NULL,
	COMPLEX_PDATE DATE NOT NULL,
	COMPLEX_STATE NUMBER NOT NULL,
	COMPLEX_INFO VARCHAR2(1000),
	COMPLEX_SUBWAY NUMBER NOT NULL,
	COMPLEX_STATION VARCHAR2(30),
	COMPLEX_FOOT NUMBER
);

